title: Roland Klahitar
logo: Roland.jpeg
#description: text below image
show_downloads: true
#theme: jekyll-theme-minimal

Solution-oriented Computer Scientist with a wide variety of professional experiences. Passionate about Cyber Security, programming, Linux System Administration, Windows Server Administration, data analysis, iOS App Development, and network troubleshooting.

### Education 
Cyber Security
Associate of Science in Computer Science
Analyst Programmer

### Work Experience 
Open Source Intelligence
Cryptography
Log Analysis 
