title: Roland Klahitar
logo: Roland.jpeg
#description: text below image
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

Solution-oriented Computer Scientist with a wide variety of professional experiences. Passionate about Cyber Security, programming, Linux System Administration, Windows Server Administration, data analysis, iOS App Development, and network troubleshooting.

### Education 
Cyber Security
Associate of Science in Computer Science
Analyst Programmer

### Work Experience 
Open Source Intelligence
Cryptography
Log Analysis 
