
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: [Roland Klahitar]
description: [My Cyber Security Portfolio]

show_downloads: "true" 
#logo: /Roland.jpeg


Solution-oriented Computer Scientist with a wide variety of professional experiences. Passionate about Cyber Security, programming, Linux System Administration, Windows Server Administration, data analysis, iOS App Development, and network troubleshooting.

### Education 
Cyber Security
Associate of Science in Computer Science
Analyst Programmer

### Work Experience 
Open Source Intelligence
Cryptography
Log Analysis 
